---
- name: Copy the sample template of server configuration
  template:
    src: server.conf.j2
    dest: /{{ base_directory }}/server.conf

- name: Copy the sample template of client configuration
  template:
    src: client.conf.j2
    dest: /{{ base_directory }}/client.conf

- name: Indicating PORT & PROTOCOL in server.conf
  lineinfile:
    dest: /{{ base_directory }}/server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: 'port 1194', line: 'port {{ PORT }}' }
    - { regexp: 'proto udp', line: 'proto {{ PROTOCOL }}' }

# === במקום ipify_facts ===
- name: Getting public IP from ipify.org
  uri:
    url: http://api.ipify.org
    return_content: yes
  register: public_ip_result

- name: Set public IP fact
  set_fact:
    ipify_public_ip: "{{ public_ip_result.content }}"

- name: Indicating PORT & PROTOCOL in client.conf
  lineinfile:
    dest: /{{ base_directory }}/client.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: 'proto udp', line: 'proto {{ PROTOCOL }}' }
    - { regexp: 'remote my-server-1 1194', line: 'remote {{ ipify_public_ip }} {{ PORT }}' }
  notify:
    - daemon_reload
    - starting_openvpn

